### ISSUE TITLE
idea: practices for storing sensitive details

### ISSUE THREAD

**Issue by shams-ahmed** [futurice/ios-good-practices#18]
details such as passwords and oauth tokens should be used in keychain. i think it would be useful in this guide... 

whats your thoughts? i can write this section up if you think it be good idea

**Comment by RyanTLX** [comment]
I would love to see a section about this topic!

**Comment by zilongqiu** [comment]
:thumbsup:

**Comment by shams-ahmed** [comment]
some feedback would be great
https://github.com/shams-ahmed/ios-good-practices/tree/topic_security

**Comment by richeterre** [comment]
Thanks for the input! It's certainly a very relevant topic. I'll have a more thorough look at your text shortly.

**Comment by richeterre** [comment]
See the merged #20.

**Comment by shams-ahmed** [comment]
@richeterre thanks! let me know if you need any help...
