### ISSUE TITLE
idea: best practices for handling app-wide appearance settings

### ISSUE THREAD

**Issue by oflannabhra** [futurice/ios-good-practices#21]
On larger apps, having a central location to set and store styling information can really simplify your project. There are various ways to go about this, from class extensions, to singletons, to just wrapping `UIAppearance` proxies. I haven't found a good summary of the advantages / disadvantages of each, but it would be nice if this project could provide one.

**Comment by eytanbiala** [comment]
+1
Including a way to make the styling flexible would also be helpful, for example if you wanted to support different themes in your app or change colors/views based on certain conditions.

**Comment by oflannabhra** [comment]
I'll try to put together a basic PR that sketches out the basic approaches to managing this.

**Comment by richeterre** [comment]
Closed for now due to inactivity. Well-founded contributions are still welcome :relaxed:
