### ISSUE TITLE
Suggestion: Best practices for Beta testing

### ISSUE THREAD

**Issue by lborgav** [futurice/ios-good-practices#25]
I'd suggest to add best practices for Beta testing. I struggled so many times to make a build available for beta testers with itunes connect, internal testers, itunes connect users, ...

**Comment by erikjalevik** [comment]
Good point. This area is a minefield.

**Comment by shams-ahmed** [comment]
+1

**Comment by tariq235** [comment]
+1

**Comment by Sebastian-Hojas** [comment]
Joining in late: We added more [details on provisioning](https://github.com/futurice/ios-good-practices#provisioning), that also includes more information on beta testing. In case you'd still want to hear more about beta testing, feel free to open a ticket again :)
