### ISSUE TITLE
Suggestion to add information about Fastlane tool

### ISSUE THREAD

**Issue by Latyntsev** [futurice/ios-good-practices#29]
Here is great tool for iOS and OS X developers, [Fastlane](http://fastlane.tools/). What do you think, if we add information about this tool?

**Comment by richeterre** [comment]
While we definitely plan to use Fastlane in upcoming projects, at Futurice we currently don't have any first-hand experience with it. Once that happens, we will amend the document accordingly. Until then, feel free to fork :wink:
