### ISSUE TITLE
Struct vs Enum for constants

### ISSUE THREAD

**Issue by aleixo** [futurice/ios-good-practices#56]
What is the difference in having one enum for constants like the following.

enum storyboardIdentifiers: String {
    
    case login = "Login"
}

**Comment by YGeorge** [comment]
It will be more convenient in the future when you add more storyboards in a project

**Comment by kiliankoe** [comment]
Using enums over structs for namespacing has the benefit of not being able to create instances by accident.

**Comment by aleixo** [comment]
I think the main problem is that i would have one primitive type for one function parameter (eg: func(xpto:String) instead of the custom enum (eg: func(xpto:EnumCustom))

**Comment by Sebastian-Hojas** [comment]
@aleixo In case you still need help, can you elaborate on your questions? What are you trying to achieve?

Are you wondering whether to use enums for Storyboard identifiers, or are you generally wondering what's the difference on enums and constants?

**Comment by kapoorsahil** [comment]
@kiliankoe We can use ```private init() { }``` for constants to avoid accidental creation of instances.

**Comment by kiliankoe** [comment]
@kapoorsahil That's definitely true. Either limit the access of the initializer or just make it downright impossible. Swift has several ways of doing pretty much everything 😉
