### ISSUE TITLE
JSON Parsing best Practice?

### ISSUE THREAD

**Issue by AliKarpuzoglu** [futurice/ios-good-practices#78]
I think the Codable type is preferred to the Libraries. (since swift 4)

https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types

**Comment by abrahamduran** [comment]
I have to admit, that at the beginning it wasn't that easy to make the transition to `Codable`. And many times I wish to go back to "easier" approaches like SwiftyJSON. Especially when dealing with an API with so many flaws and bad practices in their JSON responses, like no consistency in structure, response, dynamic keys, etc.

But, in the end, `Codable` proved to be really great to use. The Codable API is really robust and able to cover many edge cases. I didn't need to go back to other JSON parsing techniques or implement workarounds for those edge cases.

**Comment by mkko** [comment]
Definitely, it's a great addition to Swift. There's a PR #69 dealing with this deficiency.

**Comment by theapache64** [comment]
PR #69 Merged. I think we can close this issue now.
